# lsi: false
# safe: true
# source: docs
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
theme: jekyll-theme-Cayman
title: Test
description: Print leaflets/stickers to persuade others.
