# lsi: false
# safe: true
# source: docs
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
theme: jekyll-theme-Cayman
title: Unaltered's homepage
description: Bookmark this to keep an eye on my project updates!
